import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { v4 as uuidv4 } from 'uuid';
import type { Conversation, Message, ModelId } from '../types';

interface AppState {
  conversations: Conversation[];
    activeConversationId: string | null;
      currentModel: ModelId;
        sidebarOpen: boolean;
          isStreaming: boolean;
            streamingMessageId: string | null;

              setCurrentModel: (model: ModelId) => void;
                setSidebarOpen: (open: boolean) => void;
                  toggleSidebar: () => void;
                    setIsStreaming: (v: boolean) => void;

                      createConversation: () => string;
                        deleteConversation: (id: string) => void;
                          setActiveConversation: (id: string | null) => void;
                            getActiveConversation: () => Conversation | null;
                              updateConversationTitle: (id: string, title: string) => void;

                                addMessage: (conversationId: string, message: Message) => void;
                                  updateLastMessage: (conversationId: string, content: string) => void;
                                    appendToLastMessage: (conversationId: string, text: string) => void;
                                      setLastMessageError: (conversationId: string) => void;
                                      }

                                      export const useStore = create<AppState>()(
                                        persist(
                                            (set, get) => ({
                                                  conversations: [],
                                                        activeConversationId: null,
                                                              currentModel: 'claude-sonnet-4-20250514',
                                                                    sidebarOpen: true,
                                                                          isStreaming: false,
                                                                                streamingMessageId: null,

                                                                                      setCurrentModel: (model) => set({ currentModel: model }),
                                                                                            setSidebarOpen: (open) => set({ sidebarOpen: open }),
                                                                                                  toggleSidebar: () => set((s) => ({ sidebarOpen: !s.sidebarOpen })),
                                                                                                        setIsStreaming: (v) => set({ isStreaming: v }),
                                                                                                        
                                                                                                              createConversation: () => {
                                                                                                                      const id = uuidv4();
                                                                                                                              const conv: Conversation = {
                                                                                                                                        id,
                                                                                                                                                  title: 'New conversation',
                                                                                                                                                            messages: [],
                                                                                                                                                                      createdAt: Date.now(),
                                                                                                                                                                                updatedAt: Date.now(),
                                                                                                                                                                                          model: get().currentModel,
                                                                                                                                                                                                  };
                                                                                                                                                                                                          set((s) => ({ conversations: [conv, ...s.conversations], activeConversationId: id }));
                                                                                                                                                                                                                  return id;
                                                                                                                                                                                                                        },
                                                                                                                                                                                                                        
                                                                                                                                                                                                                              deleteConversation: (id) =>
                                                                                                                                                                                                                                      set((s) => {
                                                                                                                                                                                                                                                const convs = s.conversations.filter((c) => c.id !== id);
                                                                                                                                                                                                                                                          const newActive = s.activeConversationId === id
                                                                                                                                                                                                                                                                      ? (convs[0]?.id ?? null)
                                                                                                                                                                                                                                                                                  : s.activeConversationId;
                                                                                                                                                                                                                                                                                            return { conversations: convs, activeConversationId: newActive };
                                                                                                                                                                                                                                                                                                    }),
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                          setActiveConversation: (id) => set({ activeConversationId: id }),
                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                getActiveConversation: () => {
                                                                                                                                                                                                                                                                                                                        const s = get();
                                                                                                                                                                                                                                                                                                                                return s.conversations.find((c) => c.id === s.activeConversationId) ?? null;
                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                            updateConversationTitle: (id, title) =>
                                                                                                                                                                                                                                                                                                                                                    set((s) => ({
                                                                                                                                                                                                                                                                                                                                                              conversations: s.conversations.map((c) => c.id === id ? { ...c, title } : c),
                                                                                                                                                                                                                                                                                                                                                                      })),
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                            addMessage: (conversationId, message) =>
                                                                                                                                                                                                                                                                                                                                                                                    set((s) => ({
                                                                                                                                                                                                                                                                                                                                                                                              conversations: s.conversations.map((c) =>
                                                                                                                                                                                                                                                                                                                                                                                                          c.id === conversationId
                                                                                                                                                                                                                                                                                                                                                                                                                        ? { ...c, messages: [...c.messages, message], updatedAt: Date.now() }
                                                                                                                                                                                                                                                                                                                                                                                                                                      : c
                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        })),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                              updateLastMessage: (conversationId, content) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      set((s) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conversations: s.conversations.map((c) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (c.id !== conversationId) return c;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const msgs = [...c.messages];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (msgs.length > 0) msgs[msgs.length - 1] = { ...msgs[msgs.length - 1], content };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { ...c, messages: msgs };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        appendToLastMessage: (conversationId, text) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                set((s) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          conversations: s.conversations.map((c) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (c.id !== conversationId) return c;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const msgs = [...c.messages];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (msgs.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const last = msgs[msgs.length - 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          msgs[msgs.length - 1] = { ...last, content: last.content + text };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return { ...c, messages: msgs };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setLastMessageError: (conversationId) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  set((s) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conversations: s.conversations.map((c) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (c.id !== conversationId) return c;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const msgs = [...c.messages];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (msgs.length > 0) msgs[msgs.length - 1] = { ...msgs[msgs.length - 1], error: true };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { ...c, messages: msgs };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { name: 'nova-store', partialize: (s) => ({ conversations: s.conversations, currentModel: s.currentModel }) }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
